test_that("check that it runs for two weeks", {
  farm <- DiseaseFarm$new(n_pigs = 123)
  farm$add_infected_pig(total_infected = 1)
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$update_daily()
  farm$disease_status()
})
